```{r warning=FALSE}
library(lme4)
# The frequency of occurrence is counted according to Sender.ID and the top 8 are filtered.
top_sender_ids <- FCMStress %>%
  count(Sender.ID) %>%
  arrange(desc(n)) %>%
  slice_head(n = 8) %>%
  pull(Sender.ID)

# Filter the data for these top 8 Sender.IDs
filtered_FCMStress <- FCMStress %>%
  filter(Sender.ID %in% top_sender_ids)

ggplot(filtered_FCMStress, aes(x = month(filtered_FCMStress$Collar_t_), y = filtered_FCMStress$ng_g, color = as.factor(Sender.ID))) +
  geom_line() + 
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, aes(group = Sender.ID), color = "black", size = 0.5) + 
  facet_grid(year(filtered_FCMStress$Collar_t_) ~ filtered_FCMStress$Sender.ID) +
  labs(title = "FCM Levels Over Time for Each Deer", x = "Month", y = "FCM Level (ng/g)", color = "Deer ID") +
  theme_minimal()
```

```{r warning=FALSE}
ggplot(filtered_FCMStress, aes(x = month(filtered_FCMStress$Collar_t_), y = filtered_FCMStress$ng_g, color = as.factor(Sender.ID))) +
  geom_line() + 
  geom_point() +
  geom_smooth(method = "loess", se = FALSE, aes(group = year(filtered_FCMStress$Collar_t_), color = "black")) + 
  facet_grid(year(filtered_FCMStress$Collar_t_) ~.) +
  labs(title = "FCM Levels Over Time for Each Deer", x = "Month", y = "FCM Level (ng/g)", color = "Deer ID") +
  theme_minimal()
```
